---
galaxy_info:
  role_name: update
  author: nephelaiio
  description: An Ansible role to update Consul cluster nodes
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags: ["update", "consul"]
dependencies: []
